/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrandsIndexRouteImport } from './routes/brands/index'
import { Route as BrandsBrandIdRouteImport } from './routes/brands/$brandId'
import { Route as BrandsCreateRouteImport } from './routes/brands/create'
import { Route as CategoriesIndexRouteImport } from './routes/categories/index'
import { Route as CategoriesCategoryIdRouteImport } from './routes/categories/$categoryId'
import { Route as CategoriesCreateRouteImport } from './routes/categories/create'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as ProductsProductIdRouteImport } from './routes/products/$productId'
import { Route as ProductsCreateRouteImport } from './routes/products/create'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsIndexRoute = BrandsIndexRouteImport.update({
  id: '/brands/',
  path: '/brands/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsBrandIdRoute = BrandsBrandIdRouteImport.update({
  id: '/brands/$brandId',
  path: '/brands/$brandId',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsCreateRoute = BrandsCreateRouteImport.update({
  id: '/brands/create',
  path: '/brands/create',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesCategoryIdRoute = CategoriesCategoryIdRouteImport.update({
  id: '/categories/$categoryId',
  path: '/categories/$categoryId',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesCreateRoute = CategoriesCreateRouteImport.update({
  id: '/categories/create',
  path: '/categories/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsCreateRoute = ProductsCreateRouteImport.update({
  id: '/products/create',
  path: '/products/create',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brands/$brandId': typeof BrandsBrandIdRoute
  '/brands/create': typeof BrandsCreateRoute
  '/categories/$categoryId': typeof CategoriesCategoryIdRoute
  '/categories/create': typeof CategoriesCreateRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/products/create': typeof ProductsCreateRoute
  '/brands/': typeof BrandsIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brands/$brandId': typeof BrandsBrandIdRoute
  '/brands/create': typeof BrandsCreateRoute
  '/categories/$categoryId': typeof CategoriesCategoryIdRoute
  '/categories/create': typeof CategoriesCreateRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/products/create': typeof ProductsCreateRoute
  '/brands': typeof BrandsIndexRoute
  '/categories': typeof CategoriesIndexRoute
  '/products': typeof ProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brands/$brandId': typeof BrandsBrandIdRoute
  '/brands/create': typeof BrandsCreateRoute
  '/categories/$categoryId': typeof CategoriesCategoryIdRoute
  '/categories/create': typeof CategoriesCreateRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/products/create': typeof ProductsCreateRoute
  '/brands/': typeof BrandsIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brands/$brandId'
    | '/brands/create'
    | '/categories/$categoryId'
    | '/categories/create'
    | '/products/$productId'
    | '/products/create'
    | '/brands/'
    | '/categories/'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brands/$brandId'
    | '/brands/create'
    | '/categories/$categoryId'
    | '/categories/create'
    | '/products/$productId'
    | '/products/create'
    | '/brands'
    | '/categories'
    | '/products'
  id:
    | '__root__'
    | '/'
    | '/brands/$brandId'
    | '/brands/create'
    | '/categories/$categoryId'
    | '/categories/create'
    | '/products/$productId'
    | '/products/create'
    | '/brands/'
    | '/categories/'
    | '/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrandsBrandIdRoute: typeof BrandsBrandIdRoute
  BrandsCreateRoute: typeof BrandsCreateRoute
  CategoriesCategoryIdRoute: typeof CategoriesCategoryIdRoute
  CategoriesCreateRoute: typeof CategoriesCreateRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  ProductsCreateRoute: typeof ProductsCreateRoute
  BrandsIndexRoute: typeof BrandsIndexRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/': {
      id: '/brands/'
      path: '/brands'
      fullPath: '/brands/'
      preLoaderRoute: typeof BrandsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/$brandId': {
      id: '/brands/$brandId'
      path: '/brands/$brandId'
      fullPath: '/brands/$brandId'
      preLoaderRoute: typeof BrandsBrandIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/create': {
      id: '/brands/create'
      path: '/brands/create'
      fullPath: '/brands/create'
      preLoaderRoute: typeof BrandsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/': {
      id: '/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$categoryId': {
      id: '/categories/$categoryId'
      path: '/categories/$categoryId'
      fullPath: '/categories/$categoryId'
      preLoaderRoute: typeof CategoriesCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/create': {
      id: '/categories/create'
      path: '/categories/create'
      fullPath: '/categories/create'
      preLoaderRoute: typeof CategoriesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/create': {
      id: '/products/create'
      path: '/products/create'
      fullPath: '/products/create'
      preLoaderRoute: typeof ProductsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrandsBrandIdRoute: BrandsBrandIdRoute,
  BrandsCreateRoute: BrandsCreateRoute,
  CategoriesCategoryIdRoute: CategoriesCategoryIdRoute,
  CategoriesCreateRoute: CategoriesCreateRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
  ProductsCreateRoute: ProductsCreateRoute,
  BrandsIndexRoute: BrandsIndexRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
