/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteRouteImport } from './routes/_admin/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AdminIndexRouteImport } from './routes/_admin/index'
import { Route as AdminBrandsIndexRouteImport } from './routes/_admin/brands/index'
import { Route as AdminBrandsBrandIdRouteImport } from './routes/_admin/brands/$brandId'
import { Route as AdminProductsIndexRouteImport } from './routes/_admin/products/index'
import { Route as AdminProductsProductIdRouteImport } from './routes/_admin/products/$productId'
import { Route as AuthLoginIndexRouteImport } from './routes/_auth/login/index'

const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBrandsIndexRoute = AdminBrandsIndexRouteImport.update({
  id: '/brands/',
  path: '/brands/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBrandsBrandIdRoute = AdminBrandsBrandIdRouteImport.update({
  id: '/brands/$brandId',
  path: '/brands/$brandId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductsProductIdRoute = AdminProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AdminIndexRoute
  '/brands/$brandId': typeof AdminBrandsBrandIdRoute
  '/products/$productId': typeof AdminProductsProductIdRoute
  '/brands/': typeof AdminBrandsIndexRoute
  '/products/': typeof AdminProductsIndexRoute
  '/login/': typeof AuthLoginIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AdminIndexRoute
  '/brands/$brandId': typeof AdminBrandsBrandIdRoute
  '/products/$productId': typeof AdminProductsProductIdRoute
  '/brands': typeof AdminBrandsIndexRoute
  '/products': typeof AdminProductsIndexRoute
  '/login': typeof AuthLoginIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_admin/': typeof AdminIndexRoute
  '/_admin/brands/$brandId': typeof AdminBrandsBrandIdRoute
  '/_admin/products/$productId': typeof AdminProductsProductIdRoute
  '/_admin/brands/': typeof AdminBrandsIndexRoute
  '/_admin/products/': typeof AdminProductsIndexRoute
  '/_auth/login/': typeof AuthLoginIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brands/$brandId'
    | '/products/$productId'
    | '/brands/'
    | '/products/'
    | '/login/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brands/$brandId'
    | '/products/$productId'
    | '/brands'
    | '/products'
    | '/login'
  id:
    | '__root__'
    | '/_admin'
    | '/_auth'
    | '/_admin/'
    | '/_admin/brands/$brandId'
    | '/_admin/products/$productId'
    | '/_admin/brands/'
    | '/_admin/products/'
    | '/_auth/login/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/': {
      id: '/_admin/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/brands/': {
      id: '/_admin/brands/'
      path: '/brands'
      fullPath: '/brands/'
      preLoaderRoute: typeof AdminBrandsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/brands/$brandId': {
      id: '/_admin/brands/$brandId'
      path: '/brands/$brandId'
      fullPath: '/brands/$brandId'
      preLoaderRoute: typeof AdminBrandsBrandIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/products/': {
      id: '/_admin/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/products/$productId': {
      id: '/_admin/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof AdminProductsProductIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBrandsBrandIdRoute: typeof AdminBrandsBrandIdRoute
  AdminProductsProductIdRoute: typeof AdminProductsProductIdRoute
  AdminBrandsIndexRoute: typeof AdminBrandsIndexRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminBrandsBrandIdRoute: AdminBrandsBrandIdRoute,
  AdminProductsProductIdRoute: AdminProductsProductIdRoute,
  AdminBrandsIndexRoute: AdminBrandsIndexRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginIndexRoute: AuthLoginIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
